import type { Furniture, Id, Meters, Room } from './model';
import { id, meters } from './geometry';
export type FurnitureDiagnostic = { furnitureId: Id; message: string };
export const createFurniture = (name: string, width: number, depth: number, height: number, source: Furniture['source'] = 'manual'): Furniture => ({ id: id(`furniture-${Date.now()}`), name, source, dimensions: { width: meters(width), depth: meters(depth), height: meters(height), unit: 'm' }, transform: { position: { x: meters(1), y: meters(0), z: meters(1) }, rotationY: 0, scale: 1 }, appearance: { color: { value: '#b98f72', colorSpace: 'srgb' } } });
export const moveFurniture = (room: Room, furnitureId: Id, x: number, z: number) => ({ ...room, furniture: room.furniture.map(f => f.id === furnitureId ? { ...f, transform: { ...f.transform, position: { ...f.transform.position, x: meters(x), z: meters(z) } } } : f) });
export const rotateFurniture = (room: Room, furnitureId: Id, rotationY: number) => ({ ...room, furniture: room.furniture.map(f => f.id === furnitureId ? { ...f, transform: { ...f.transform, rotationY } } : f) });
export const resizeFurniture = (room: Room, furnitureId: Id, width: number) => ({ ...room, furniture: room.furniture.map(f => { if (f.id !== furnitureId) return f; const ratio = width / f.dimensions.width; return { ...f, dimensions: { ...f.dimensions, width: meters(width), depth: meters(f.dimensions.depth * ratio), height: meters(f.dimensions.height * ratio) }, transform: { ...f.transform, scale: f.transform.scale * ratio } }; }) });
export const deleteFurniture = (room: Room, furnitureId: Id) => ({ ...room, furniture: room.furniture.filter(f => f.id !== furnitureId) });
const overlap = (a: Furniture, b: Furniture) => Math.abs(a.transform.position.x-b.transform.position.x) < (a.dimensions.width+b.dimensions.width)/2 && Math.abs(a.transform.position.z-b.transform.position.z) < (a.dimensions.depth+b.dimensions.depth)/2;
export function diagnoseFurniture(room: Room): FurnitureDiagnostic[] { const out: FurnitureDiagnostic[]=[]; room.furniture.forEach((f,i) => { const x=f.transform.position.x, z=f.transform.position.z; if(x-f.dimensions.width/2<0||z-f.dimensions.depth/2<0||x+f.dimensions.width/2>room.dimensions.width||z+f.dimensions.depth/2>room.dimensions.depth) out.push({furnitureId:f.id,message:`${f.name} is outside the room bounds.`}); room.furniture.slice(i+1).filter(g=>overlap(f,g)).forEach(g=>out.push({furnitureId:f.id,message:`${f.name} overlaps ${g.name}; move one item.`})); }); return out; }
