import type { Asset, Id, ProjectSnapshot } from '../domain/model';
import { isValidProject } from '../domain/validation';
export const STORAGE_VERSION = 1 as const;
export type SerializedProject = { version: typeof STORAGE_VERSION; project: ProjectSnapshot };
export interface ProjectRepository { save(project: ProjectSnapshot): Promise<void>; load(): Promise<ProjectSnapshot | undefined>; clear(): Promise<void> }
export interface AssetStore { put(asset: Asset): Promise<void>; get(id: Id): Promise<Asset | undefined>; remove(id: Id): Promise<void> }
export function serializeProject(project: ProjectSnapshot): string { if (!isValidProject(project)) throw new Error('Cannot save an invalid project.'); return JSON.stringify({ version: STORAGE_VERSION, project }); }
export function deserializeProject(raw: string): ProjectSnapshot { let parsed: unknown; try { parsed=JSON.parse(raw); } catch { throw new Error('Saved project is corrupt. Export or clear local data and try again.'); } const envelope=parsed as Partial<SerializedProject>; if (envelope.version !== STORAGE_VERSION) throw new Error(`Unsupported saved project version: ${String(envelope.version)}.`); if (!isValidProject(envelope.project)) throw new Error('Saved project failed validation and was not loaded.'); return envelope.project; }
export function createLocalRepository(storage: Storage = localStorage, key = 'home-designer:project'): ProjectRepository { return { async save(project) { try { storage.setItem(key, serializeProject(project)); } catch { throw new Error('Could not save project: browser storage quota may be full.'); } }, async load() { const raw=storage.getItem(key); return raw ? deserializeProject(raw) : undefined; }, async clear() { storage.removeItem(key); } }; }
export function migrateProject(raw: string): string { const parsed=JSON.parse(raw) as { version?: number; project?: ProjectSnapshot }; if (parsed.version === 1) return raw; throw new Error(`Unsupported saved project version: ${String(parsed.version)}.`); }
